extends SceneTree
const Farm=preload("res://farm/farm_state.gd")
const Store=preload("res://farm/farm_store.gd")
const Decor=preload("res://farm/decoration_state.gd")
const Animals=preload("res://farm/animal_companions.gd")
var failures: int=0
func _initialize() -> void: run.call_deferred()
func check(ok: bool,label: String) -> void:
	if not ok: failures+=1;push_error(label)
func run() -> void:
	var farm:=Farm.new(1000)
	var data: Dictionary=farm.snapshot();data.inventory.greens=2;farm.restore_snapshot(data)
	var initial: Dictionary=farm.snapshot()
	check(farm.animal_action("LakeDuck1","name","小雨",0).ok,"Rename")
	check(farm.animal_action("LakeDuck1","preference",2,1).ok,"Rest preference")
	check(farm.animal_action("LakeDuck1","feed","greens",2).ok,"Share food")
	check(not farm.animal_action("LakeDuck1","feed","greens",2).ok,"Duplicate food request rejected")
	check(farm.snapshot().inventory.greens==1 and farm.snapshot().harvested==initial.harvested,"Exactly one basket spent, achievements preserved")
	var before: Dictionary=farm.snapshot()
	check(not farm.animal_action("LakeDuck1","name","\n",3).ok,"Reject control characters")
	check(not farm.animal_action("LakeDuck1","name","名字超过十二个汉字就不应该允许了",3).ok,"Bound name")
	check(not farm.animal_action("LakeDuck1","preference",4,3).ok,"Bound rest setting")
	check(not farm.animal_action("LakeDuck1","feed","garlic",3).ok,"Only supported leaf food")
	check(farm.snapshot()==before,"Failures don't change state")
	check(farm.animal_action("YardHen1","call",null,0).ok,"Free call without food")
	farm.settle(9999999999.0)
	check(farm.snapshot().animals.LakeDuck1==before.animals.LakeDuck1,"Long absence never reduces familiarity or loses name")
	var path: String=ProjectSettings.globalize_path("res://../.local/verification/animal-state-%d"%Time.get_ticks_usec())
	var store:=Store.new(path);store.load_state()
	check(store.save(farm.snapshot(),Decor.new().snapshot()).ok,"Persist current schema")
	var loaded: Dictionary=Store.new(path).load_state()
	check(loaded.ok and loaded.farm.animals==farm.snapshot().animals,"JSON round trip keeps all seven identities and settings")
	var invalid: Dictionary=farm.snapshot();invalid.animals.YardHen2.preference=1.5
	check(not farm.restore_snapshot(invalid),"Invalid persisted preference rejected")
	print("ANIMAL_COMPANIONS failures=",failures," directory=",path)
	quit(0 if failures==0 else 1)
